// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action @new;
    
    private Gtk.Action open;
    
    private Gtk.Action save;
    
    private Gtk.Action apply;
    
    private Gtk.Action properties;
    
    private Gtk.Action quit;
    
    private Gtk.Action File;
    
    private Gtk.Action Nuevo;
    
    private Gtk.Action Abrir;
    
    private Gtk.Action Guardar;
    
    private Gtk.Action Export;
    
    private Gtk.Action Salir;
    
    private Gtk.Action ToXml;
    
    private Gtk.Action ToIptablesSaveFormat;
    
    private Gtk.VBox vbox3;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.Toolbar toolbar1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.TreeView treeview2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.@new = new Gtk.Action("new", null, null, "gtk-new");
        w2.Add(this.@new, null);
        this.open = new Gtk.Action("open", null, null, "gtk-open");
        w2.Add(this.open, null);
        this.save = new Gtk.Action("save", null, null, "gtk-save");
        w2.Add(this.save, null);
        this.apply = new Gtk.Action("apply", null, null, "gtk-apply");
        w2.Add(this.apply, null);
        this.properties = new Gtk.Action("properties", null, null, "gtk-properties");
        w2.Add(this.properties, null);
        this.quit = new Gtk.Action("quit", null, null, "gtk-quit");
        w2.Add(this.quit, null);
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w2.Add(this.File, null);
        this.Nuevo = new Gtk.Action("Nuevo", Mono.Unix.Catalog.GetString("_Nuevo"), null, "gtk-new");
        this.Nuevo.ShortLabel = Mono.Unix.Catalog.GetString("_Nuevo");
        w2.Add(this.Nuevo, null);
        this.Abrir = new Gtk.Action("Abrir", Mono.Unix.Catalog.GetString("_Abrir"), null, "gtk-open");
        this.Abrir.ShortLabel = Mono.Unix.Catalog.GetString("_Abrir");
        w2.Add(this.Abrir, null);
        this.Guardar = new Gtk.Action("Guardar", Mono.Unix.Catalog.GetString("_Guardar"), null, "gtk-save");
        this.Guardar.ShortLabel = Mono.Unix.Catalog.GetString("_Guardar");
        w2.Add(this.Guardar, null);
        this.Export = new Gtk.Action("Export", Mono.Unix.Catalog.GetString("Export"), null, null);
        this.Export.ShortLabel = Mono.Unix.Catalog.GetString("Export");
        w2.Add(this.Export, null);
        this.Salir = new Gtk.Action("Salir", Mono.Unix.Catalog.GetString("_Salir"), null, "gtk-quit");
        this.Salir.ShortLabel = Mono.Unix.Catalog.GetString("_Salir");
        w2.Add(this.Salir, null);
        this.ToXml = new Gtk.Action("ToXml", Mono.Unix.Catalog.GetString("To xml"), null, null);
        this.ToXml.ShortLabel = Mono.Unix.Catalog.GetString("To xml");
        w2.Add(this.ToXml, null);
        this.ToIptablesSaveFormat = new Gtk.Action("ToIptablesSaveFormat", Mono.Unix.Catalog.GetString("To iptables-save format"), null, null);
        this.ToIptablesSaveFormat.ShortLabel = Mono.Unix.Catalog.GetString("To iptables-save format");
        w2.Add(this.ToIptablesSaveFormat, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.Icon = Gtk.IconTheme.Default.LoadIcon("stock_smiley-6", 16, 0);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.BorderWidth = ((uint)(2));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='Nuevo'/><menuitem action='Abrir'/><menuitem action='Guardar'/><menu action='Export'><menuitem action='ToXml'/><menuitem action='ToIptablesSaveFormat'/></menu><menuitem action='Salir'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox3.Add(this.menubar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.menubar1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='new'/><toolitem action='open'/><toolitem action='save'/><toolitem action='apply'/><toolitem action='properties'/><toolitem action='quit'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar1.IconSize = ((Gtk.IconSize)(2));
        this.vbox3.Add(this.toolbar1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.toolbar1]));
        w4.Position = 1;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.treeview2 = new Gtk.TreeView();
        this.treeview2.CanFocus = true;
        this.treeview2.Name = "treeview2";
        this.hbox2.Add(this.treeview2);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.treeview2]));
        w5.Position = 0;
        this.vbox3.Add(this.hbox2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
        w6.Position = 2;
        this.Add(this.vbox3);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 518;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
