// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action NewFile;
    
    private Gtk.Action OpenFile;
    
    private Gtk.Action SaveToFile;
    
    private Gtk.Action ApplyChangesToFirewall;
    
    private Gtk.Action Configure;
    
    private Gtk.Action quit;
    
    private Gtk.Action File;
    
    private Gtk.Action Nuevo;
    
    private Gtk.Action Abrir;
    
    private Gtk.Action Guardar;
    
    private Gtk.Action Export;
    
    private Gtk.Action Salir;
    
    private Gtk.Action ToXml;
    
    private Gtk.Action ToIptablesSaveFormat;
    
    private Gtk.VBox vbox3;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.Toolbar toolbar1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.TreeView treeview2;
    
    private Gtk.VButtonBox vbuttonbox1;
    
    private Gtk.Button button3;
    
    private Gtk.Button button4;
    
    private Gtk.Button button6;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.NewFile = new Gtk.Action("NewFile", Mono.Unix.Catalog.GetString("New file"), Mono.Unix.Catalog.GetString("Create a new firewall rules definition file"), "gtk-new");
        this.NewFile.ShortLabel = Mono.Unix.Catalog.GetString("New file");
        w2.Add(this.NewFile, null);
        this.OpenFile = new Gtk.Action("OpenFile", Mono.Unix.Catalog.GetString("Open file"), Mono.Unix.Catalog.GetString("Open a firewall rule definition file"), "gtk-open");
        this.OpenFile.ShortLabel = Mono.Unix.Catalog.GetString("Open file");
        w2.Add(this.OpenFile, null);
        this.SaveToFile = new Gtk.Action("SaveToFile", Mono.Unix.Catalog.GetString("Save to file"), Mono.Unix.Catalog.GetString("Save changes to a file"), "gtk-save");
        this.SaveToFile.ShortLabel = Mono.Unix.Catalog.GetString("Save to file");
        w2.Add(this.SaveToFile, null);
        this.ApplyChangesToFirewall = new Gtk.Action("ApplyChangesToFirewall", Mono.Unix.Catalog.GetString("Apply changes to firewall"), Mono.Unix.Catalog.GetString("Apply changes to firewall."), "gtk-apply");
        this.ApplyChangesToFirewall.ShortLabel = Mono.Unix.Catalog.GetString("Apply changes");
        w2.Add(this.ApplyChangesToFirewall, null);
        this.Configure = new Gtk.Action("Configure", Mono.Unix.Catalog.GetString("Configure"), Mono.Unix.Catalog.GetString("Configure the application"), "gtk-properties");
        this.Configure.ShortLabel = Mono.Unix.Catalog.GetString("Configure");
        w2.Add(this.Configure, null);
        this.quit = new Gtk.Action("quit", null, null, "gtk-quit");
        w2.Add(this.quit, null);
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w2.Add(this.File, null);
        this.Nuevo = new Gtk.Action("Nuevo", Mono.Unix.Catalog.GetString("_Nuevo"), null, "gtk-new");
        this.Nuevo.ShortLabel = Mono.Unix.Catalog.GetString("_Nuevo");
        w2.Add(this.Nuevo, null);
        this.Abrir = new Gtk.Action("Abrir", Mono.Unix.Catalog.GetString("_Abrir"), null, "gtk-open");
        this.Abrir.ShortLabel = Mono.Unix.Catalog.GetString("_Abrir");
        w2.Add(this.Abrir, null);
        this.Guardar = new Gtk.Action("Guardar", Mono.Unix.Catalog.GetString("_Guardar"), null, "gtk-save");
        this.Guardar.ShortLabel = Mono.Unix.Catalog.GetString("_Guardar");
        w2.Add(this.Guardar, null);
        this.Export = new Gtk.Action("Export", Mono.Unix.Catalog.GetString("Export"), null, null);
        this.Export.ShortLabel = Mono.Unix.Catalog.GetString("Export");
        w2.Add(this.Export, null);
        this.Salir = new Gtk.Action("Salir", Mono.Unix.Catalog.GetString("_Salir"), null, "gtk-quit");
        this.Salir.ShortLabel = Mono.Unix.Catalog.GetString("_Salir");
        w2.Add(this.Salir, null);
        this.ToXml = new Gtk.Action("ToXml", Mono.Unix.Catalog.GetString("To xml"), null, null);
        this.ToXml.ShortLabel = Mono.Unix.Catalog.GetString("To xml");
        w2.Add(this.ToXml, null);
        this.ToIptablesSaveFormat = new Gtk.Action("ToIptablesSaveFormat", Mono.Unix.Catalog.GetString("To iptables-save format"), null, null);
        this.ToIptablesSaveFormat.ShortLabel = Mono.Unix.Catalog.GetString("To iptables-save format");
        w2.Add(this.ToIptablesSaveFormat, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.Icon = Stetic.IconLoader.LoadIcon("stock_smiley-6", 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.BorderWidth = ((uint)(2));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='Nuevo'/><menuitem action='Abrir'/><menuitem action='Guardar'/><separator/><menu action='Export'><menuitem action='ToXml'/><menuitem action='ToIptablesSaveFormat'/></menu><separator/><menuitem action='Salir'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox3.Add(this.menubar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.menubar1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='NewFile'/><toolitem action='OpenFile'/><toolitem action='SaveToFile'/><separator/><toolitem action='Configure'/><separator/><toolitem action='ApplyChangesToFirewall'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
        Gtk.Tooltips w4 = new Gtk.Tooltips();
        w4.SetTip(this.toolbar1, "New rule file", "New rule file");
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar1.IconSize = ((Gtk.IconSize)(2));
        this.vbox3.Add(this.toolbar1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.toolbar1]));
        w5.Position = 1;
        w5.Expand = false;
        w5.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.treeview2 = new Gtk.TreeView();
        this.treeview2.CanFocus = true;
        this.treeview2.Name = "treeview2";
        this.treeview2.RulesHint = true;
        this.hbox2.Add(this.treeview2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.treeview2]));
        w6.Position = 0;
        // Container child hbox2.Gtk.Box+BoxChild
        this.vbuttonbox1 = new Gtk.VButtonBox();
        this.vbuttonbox1.Name = "vbuttonbox1";
        this.vbuttonbox1.Spacing = 6;
        this.vbuttonbox1.BorderWidth = ((uint)(2));
        this.vbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseStock = true;
        this.button3.UseUnderline = true;
        this.button3.Label = "gtk-add";
        this.vbuttonbox1.Add(this.button3);
        Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button3]));
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.button4 = new Gtk.Button();
        this.button4.CanFocus = true;
        this.button4.Name = "button4";
        this.button4.UseStock = true;
        this.button4.UseUnderline = true;
        this.button4.Label = "gtk-remove";
        this.vbuttonbox1.Add(this.button4);
        Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button4]));
        w8.Position = 1;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.button6 = new Gtk.Button();
        this.button6.CanFocus = true;
        this.button6.Name = "button6";
        this.button6.UseStock = true;
        this.button6.UseUnderline = true;
        this.button6.Label = "gtk-edit";
        this.vbuttonbox1.Add(this.button6);
        Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button6]));
        w9.Position = 2;
        w9.Expand = false;
        w9.Fill = false;
        this.hbox2.Add(this.vbuttonbox1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbuttonbox1]));
        w10.Position = 1;
        w10.Expand = false;
        w10.Fill = false;
        this.vbox3.Add(this.hbox2);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
        w11.Position = 2;
        this.Add(this.vbox3);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 518;
        this.DefaultHeight = 379;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
